### ISSUE TITLE
Compile/ Runtime error

### ISSUE THREAD

**Issue by dave1977usa** [isukces/cs2php#8]
**When attempting to execute the compiled EXE file on a C# project, I receive compilation errors** (Please see commandline snapshot)

![cs2php-error](https://user-images.githubusercontent.com/34048382/33340558-443146e6-d431-11e7-8716-694b2b144aa3.JPG)

**While Building the Solution, I receive some warnings such as below:**

![errs](https://user-images.githubusercontent.com/34048382/33340782-ed6ad236-d431-11e7-8608-0fe8e7ae3486.JPG)

Can you please give me some hints?

Thanks!
David

**Comment by isukces** [comment]
I also have problem with cooperation between cs2php and roslyn. Unfortunatelly I have no hint at this moment. :(
In my opinion problem source is msbuild used behind. It processes a bunch of *.targets files that is out of control by cs2php.

**Comment by stylixpro** [comment]
Same error here.
When I compile a few month ago, it was success.
I think I didn't change my development environment.
Today I tried to compile again, 
"No value for runtime metadata version" error occurred.
What have changed meanwhile?

**Comment by isukces** [comment]
Seems that problem is SOLVED.
If you still have stupid compilation error related to "System.String" please do following:
- close Visual Studio
- clean Visual Studio cache files. I did it manuall by removing all `ComponentModelCache` and  `ShadowCache` folders under `C:\Users\{USERNAME}\AppData\Local\Microsoft\VisualStudio` (i.e. `c:\Users\{USERNAME}\AppData\Local\Microsoft\VisualStudio\15.0_e6b29d83\Designer\ShadowCache` )
- delete all bin and obj folders in CS2PHP solution folder
- delete all *.cache files under CS2PHP solution folder
- run `nuget restore` manually
- open Visual Studio and recompile solution again
It was tested on Visual Studio Community 2017, Version 15.5.3
